//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMCDriveShare_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatThread
    {
        public long ThreadId { get; set; }
        public string User1Id { get; set; }
        public string User2Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime LastPostedOnDate { get; set; }
    
        public virtual AspNetUser User1 { get; set; }
        public virtual AspNetUser User2 { get; set; }
    }
}
