//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMCDriveShare_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public long ThreadId { get; set; }
        public int MessageOrder { get; set; }
        public string FromUserId { get; set; }
        public string ToUserId { get; set; }
        public System.DateTime DateSent { get; set; }
        public bool IsBlocked { get; set; }
        public bool IsSent { get; set; }
        public bool IsFailed { get; set; }
        public string MessageContent { get; set; }
    
        public virtual AspNetUser Sender { get; set; }
        public virtual AspNetUser Receiver { get; set; }
        public virtual ChatThread ChatThread { get; set; }
    }
}
