//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMCDriveShare_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilePicture
    {
        public string UserId { get; set; }
        public bool IsVehiclePicture { get; set; }
        public byte[] PictureContent { get; set; }
    
        public virtual AspNetUser User { get; set; }
    }
}
