//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMCDriveShare_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.Riders = new HashSet<AspNetUser>();
        }
    
        public string DriverId { get; set; }
        public int RouteNum { get; set; }
        public int ScheduleId { get; set; }
        public Nullable<int> DestinationId { get; set; }
        public System.TimeSpan DepartTime { get; set; }
        public System.TimeSpan ArriveTime { get; set; }
        public Nullable<int> MaxSeatCount { get; set; }
    
        public virtual AspNetUser Driver { get; set; }
        public virtual Schedule Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> Riders { get; set; }
        public virtual Geolocation Geolocation { get; set; }
    }
}
