//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMCDriveShare_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserLocations
    {
        public string locationId { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> isDriver { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<decimal> latitude { get; set; }
    }
}
