//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMCDriveShare.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DriveShareEntities3 : DbContext
    {
        public DriveShareEntities3()
            : base("name=DriveShareEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Geolocation> Geolocations { get; set; }
        public virtual DbSet<RideBoard> RideBoards { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int AddNewUser(string firstName, string lastName, string username, string phoneNumber, Nullable<bool> isDriver, string nmcEmail, string password, string gender)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            var isDriverParameter = isDriver.HasValue ?
                new ObjectParameter("isDriver", isDriver) :
                new ObjectParameter("isDriver", typeof(bool));
    
            var nmcEmailParameter = nmcEmail != null ?
                new ObjectParameter("nmcEmail", nmcEmail) :
                new ObjectParameter("nmcEmail", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddNewUser", firstNameParameter, lastNameParameter, usernameParameter, phoneNumberParameter, isDriverParameter, nmcEmailParameter, passwordParameter, genderParameter);
        }
    }
}
